name: {{ cookiecutter.module_name }}

channels:
    - astropy

dependencies:
    - python>={{ cookiecutter.minimum_python_version }}
    - astropy
    - Cython
    - matplotlib
    - numpy
#   - pip:
#       - dependency_from_pip
